package ReverseModule;


/**
* ReverseModule/_ReverseImplBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ReverseModule.idl
* Friday, May 19, 2023 11:00:10 AM GMT
*/

public abstract class _ReverseImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements ReverseModule.Reverse, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ReverseImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("reverse_string", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ReverseModule/Reverse/reverse_string
       {
         String str = in.read_string ();
         String __result = null;
         __result = this.reverse_string (str);
         out = rh.createReply();
         out.write_string (__result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ReverseModule/Reverse:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }


} // class _ReverseImplBase
