package ReverseModule;


/**
* ReverseModule/Reverse.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ReverseModule.idl
* Friday, May 19, 2023 11:00:10 AM GMT
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
