package ReverseModule;


/**
* ReverseModule/ReverseOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ReverseModule.idl
* Friday, May 19, 2023 11:00:10 AM GMT
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
